### ISSUE TITLE
Brightness not restored all the way after multiple clicks

### ISSUE THREAD

**Issue by tschottdorf** [brhs/nomouse#3]
To repro (OSX 10.12.3):

- run `bin/nomouse`
- click a few times (>10 should turn off screen)
- wait 6.66 seconds
- observe that brightness gets restored only to minimal brightness, but not the original one.

Or maybe it doesn't get restored at all with the exception of turning on the screen again when it hits rock bottom? Either way, this can't be hard to fix

**Comment by brhs** [comment]
It takes 6.66 seconds to restore the effects of dimming from each click. If you click 10 times, it'll take 66.6 seconds.
