### ISSUE TITLE
Feature: Multi display dim

### ISSUE THREAD

**Issue by andreimc** [brhs/nomouse#5]
CGGetActiveDisplayList using this to get all display and dim them would possibly be better.

**Comment by andreiglingeanu** [comment]
Yeah, I've also noticed that. It changes brightness only for the main display.

**Comment by brhs** [comment]
I'm new to Objective C. The function signature is:

```
CGError CGGetActiveDisplayList(uint32_t maxDisplays, CGDirectDisplayID *activeDisplays, uint32_t *displayCount);
```

In this case, am I meant to malloc an array of `CGDirectDisplayID`s, or use something managed like `NSMutableArray`?

**Comment by brhs** [comment]
Fixed.
